### ISSUE TITLE
Minimum WP Version for Production?

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-website#10]
Hi @amostajo 

Was curious what the minimum WP version that the WPMVC framework supports and if that should be disclosed in the documentation here;
https://www.wordpress-mvc.com/v1/get-started/#requirements

Thanks

**Comment by amostajo** [comment]
@garretthyder The minimum is 5.4 which is indicated in the `composer.json` file, although this should be indicated in the requirements.
