### ISSUE TITLE
Docs: Basic Ayuco Create Command missing termmodel

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-website#7]
Hi @amostajo 

In The Basics > Ayuco > Create Command, the termmodel object isn't listed here;
https://www.wordpress-mvc.com/v1/ayuco/
It's available in the code and in the MVC > Term Models documentation here;
https://www.wordpress-mvc.com/v1/term-models/

Just flagging to add it to the getting started as it's where most users will learn what objects are available.

Cheers

**Comment by amostajo** [comment]
Thy
