### ISSUE TITLE
In the requirements  do we need `> v10` for node still

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-website#9]
Hi @amostajo with your latest updates should the `(< v.10)` requirement be removed from beside NodeJS?
https://www.wordpress-mvc.com/v1/get-started/#requirements

**Comment by amostajo** [comment]
While Node and node-sass have the right versions, it appears gulp is requesting v4 on node 10, so it is not ready until gulp is migrated.

**Comment by amostajo** [comment]
Release notes + migration blog article needed.
